import {
  Css3,
  Cursor,
  ExpressJs,
  Github,
  Html5,
  Javascript,
  NestJS,
  NextJs,
  Nodejs,
  PostgreSQL,
  Prisma,
  ReactJs,
  Redux,
  Tailwindcss,
  Typescript,
  VisualStudioCode,
  Vuejs,
} from "../components/shared/icons/Technologies";

export const techLogos = [
  { node: <Html5 />, title: "Html5" },
  { node: <Css3 />, title: "Css3" },
  { node: <Javascript />, title: "Javascript" },
  { node: <Typescript />, title: "Typescript" },
  { node: <Vuejs />, title: "Vue.js" },
  { node: <ReactJs />, title: "React.js" },
  { node: <NextJs />, title: "Next.js" },
  { node: <Tailwindcss />, title: "Tailwindcss" },
  { node: <Redux />, title: "Redux" },
  { node: <Nodejs />, title: "Node.js" },
  { node: <ExpressJs />, title: "Express.js" },
  { node: <NestJS />, title: "NestJS" },
  { node: <Prisma />, title: "Prisma" },
  { node: <PostgreSQL />, title: "PostgreSQL" },
  { node: <Github />, title: "Github" },
  { node: <Cursor />, title: "Cursor" },
  { node: <VisualStudioCode />, title: "VSCode" },
];
